title: Digital Detox 
email: jolayfield@gmail.com
baseurl: "/digital_detox" # the subpath of your site, e.g. /blog
url: "https://jolayfield.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jolayfield   
tagline: A Compilation of Thoughts 
author: Joshua Layfield 
# Build settings
theme: minima
plugins:
- jekyll-feed
